"""add unique constraint to holdings

Revision ID: 62e8d9e69528
Revises: 6d7ff797b4e6
Create Date: 2026-02-03 14:22:47.916536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e8d9e69528'
down_revision = '6d7ff797b4e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_holding_portfolio_symbol', 'holdings', ['portfolio_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_holding_portfolio_symbol', 'holdings', type_='unique')
    # ### end Alembic commands ###
